---
title: "week2"
output: html_document
---

DEPENDENCIES
```{r}
install.packages("prettyR")
library(prettyR)

install.packages("binom")
library(binom)

install.packages("Epi")
library(Epi)
```


CONSTANTSS
```{r}
pathSmp1 <- "./data/smp1.csv"
```


IMPORT DATA
```{r}
smp <- read.csv2(pathSmp1)
```


intervalle de confience à la main
```{r}
descr <- describe(smp$age)
descr_2 <- descr$Numeric$x
age_mean <- descr_2["mean"]

get_intervall <- function(mean, sd, valid.n, direction = "down") {
  d <- -1
  if (direction == "up") {
    d <- 1
  }
  return(mean + d * 1.96 * sd / sqrt(valid.n))
}

down <- get_intervall(age_mean, descr_2["valid.n"], descr_2["sd"])
up <- get_intervall(age_mean, descr_2["valid.n"], descr_2["sd"], "up")
```

```{r}
binom.confint(3, 10, methods = "all")
```
Method = "exact" => la meilleure



## Coef de correlation de Pearson (r)

```{r}
plot(jitter(smp$age), jitter(smp$n.enfant))
```

r =
```{r}
cor(smp$age, smp$n.enfant, use = "complete.obs")
```

## Force de liaison entre 2 variables binaires

```{r}
smp$ed.b <- ifelse(smp$ed > 2, 1, 0)

# vérification :
table(smp$ed.b, smp$ed, deparse.level = 2, useNA = "always")
```

Table de comparaison 2 à 2 :
(le "1 -" c'est parce que twoby2 considère que 1 c'est la présence d'anomalie et 0 non)
```{r}
twoby2(1 - smp$ed.b, 1 - smp$dep.cons)
```
































